[WIP] Multi contracts support
AstarNetwork/swanky-cli pull request #14
Opened 2022-09-20 05:41 UTC by shunsukew

2022-09-20 05:47 UTC, shunsukew commented
@codespool 
Please let me know if you have a good idea for naming this command. I use `scaffold` for now.
I think it is also an option to put several commands related to contracts together as subcommands of `swanky contract`.

2022-09-20 08:11 UTC, codespool commented
> @codespool Please let me know if you have a good idea for naming this command. I use `scaffold` for now. I think it is also an option to put several commands related to contracts together as subcommands of `swanky contract`. (e.g. `swanky contract new`, `swanky contract call`, `swanky contract deploy`)

I agree, the `swanky contract` command is the way to go.
So `deploy`, `compile` and `call` should all be subcommands (and `new`)

contract name should be the required argument for all, so for example
`swanky contract call flipper`, `swanky contract deploy my_psp22`

2022-09-21 02:43 UTC, shunsukew commented
> > @codespool Please let me know if you have a good idea for naming this command. I use `scaffold` for now. I think it is also an option to put several commands related to contracts together as subcommands of `swanky contract`. (e.g. `swanky contract new`, `swanky contract call`, `swanky contract deploy`)
> 
> I agree, the `swanky contract` command is the way to go. So `deploy`, `compile` and `call` should all be subcommands (and `new`)
> 
> contract name should be the required argument for all, so for example `swanky contract call flipper`, `swanky contract deploy my_psp22`

Updated!

2022-09-21 03:17 UTC, shunsukew commented
>

2022-09-21 03:28 UTC, shunsukew commented
> > > @codespool Please let me know if you have a good idea for naming this command. I use `scaffold` for now. I think it is also an option to put several commands related to contracts together as subcommands of `swanky contract`. (e.g. `swanky contract new`, `swanky contract call`, `swanky contract deploy`)
> > 
> > 
> > I agree, the `swanky contract` command is the way to go. So `deploy`, `compile` and `call` should all be subcommands (and `new`)
> > contract name should be the required argument for all, so for example `swanky contract call flipper`, `swanky contract deploy my_psp22`
> 
> Updated!

As for `swanky contract call` command,
1. 1 contract can have multiple instances with different addresses.
2. personally think swanky-cli should be able to call any contracts which exist on a target chain.

So, rather than taking CONTRACT_NAME as required args, CONTRACT_ADDRESS. this should be also required arg instead of a flag.

2022-09-21 16:05 UTC, codespool commented
The `call` command needs a full rewrite, to include what you mentioned, as well as use polkadot.js API, but it didn't make sense to do it until we had multiple contracts and accounts support.
I'll create a separate ticket for it.

2022-09-21 18:18 UTC, codespool requested changes
Couple of minor changes, but great job overall! 👍

2022-09-21 18:18 UTC, codespool commented on src/commands/contract/new.ts
> +    if (fs.existsSync(path.join(projectPath, "contracts", args.contractName))) {
better to use `pathExists` provided by fs-extra:
https://github.com/jprichardson/node-fs-extra/blob/master/docs/pathExists.md
(or sync version)

2022-09-21 18:18 UTC, codespool commented on src/lib/tasks.ts
>    await copy(contractTemplatePath, path.resolve(projectPath, "contracts", contractName));
maybe call `copyContractTemplateFiles` here as well

2022-09-22 02:32 UTC, shunsukew commented on src/commands/contract/compile.ts
> +import { args } from "@oclif/core/lib/parser";
sorry it's no need at all

2022-09-22 08:11 UTC, codespool approved these changes
LGTM 👍

2022-09-22 08:21 UTC, merged